# Travis CI for OSXvnc.

os: osx

addons:
before_deploy:
before_install:
branches:
compiler:
deploy:
dist:
matrix:
notification:
sudo:
  # TODO

install:
  - brew install libjpeg

script:
  - xcodebuild
