#!/bin/sh 
#
# OSXvnc-keepalive 
#
# This little script, as you might imagine, will relaunch OSXvnc-server
# when a user logs out and the OS kills the process (because it's running an event loop)
# 
# Modification Log:
#
# 1.33
# Modified so that keepalive only shuts down on unrecoverable errors
#
# 1.31
# Modified so that OSXvnc can live in directories with spaces
#
# 1.11
# Initial version

RESULT=15

# OS X will send a SIGINT or SIGTERM to shutdown OSXvnc-server
# On a negative SIGNAL we'll stop properly (this is what the server returns internally when an error occurs)
while [ "$RESULT" > "0" ]
do
	echo "OSXVNC: Starting Server"
	"$@"
	RESULT=$?
	sleep 6
done

echo "OSXVNC Shutdown with exit status" $RESULT

