#!/bin/sh 
. /etc/rc.common

#
# Start OSXvnc Version 1.3
# 
# The OSXvnc application will OVERWRITE this file if you ask it to Setup the Startup Item
#

VNCPATH=/Applications/OSXvnc.app
VNCARGS="-rfbport 5900 -rfbauth $VNCPATH/.osxvncauth -swapButtons -dontdisconnect"

#
# Modification Log:
#
# 1.3
# Modified so that OSXvnc app can configure
# Removed Usage
#
# 1.2
# Fixed problem in stop section (missing space)
# Fixed stop to also kill the server and keep alive
# Now Uses $VNCPATH for other arguments
#
# 1.11
# Added Usage Info
# Added keepalive call
#
# 1.0/Initial
# Initial Version, no # and no history
#
##

if [ ${1:-noset} = "setpassword" ]; then
  $VNCPATH/storepasswd "$2" $VNCPATH/.osxvncauth
  echo "Password set at path " $VNCPATH/.osxvncauth
  exit 0
fi

if [ ${1:-noset} = "stop" ]; then
  ConsoleMessage "Stopping OSXvnc Server"

  OSXVNCPID=`/bin/ps -auxwwww | grep OSXvnc-keepalive | grep -v grep | awk 'NF > 2 {print \$2}'`
  if [ "${OSXVNCPID:=""}" ]; then
    kill $OSXVNCPID
  fi

  OSXVNCPID=`/bin/ps -auxwwww | grep OSXvnc-keepalive | grep -v grep | awk 'NF > 2 {print \$2}'`
  if [ "${OSXVNCPID:=""}" != "" ]; then
	ConsoleMessage "OSXvnc stop: problem stopping OSXvnc-keepalive"
        exit -1
  else
#   Now Kill OSXvnc
    OSXVNCPID=`/bin/ps -auxwwww | grep OSXvnc-server | grep -v grep | awk 'NF > 2 {print \$2}'`
    if [ "${OSXVNCPID:=""}" ]; then
      kill $OSXVNCPID
    fi
    OSXVNCPID=`/bin/ps -auxwwww | grep OSXvnc-server | grep -v grep | awk 'NF > 2 {print \$2}'`
    if [ "${OSXVNCPID:=""}" != "" ]; then
        ConsoleMessage "OSXvnc stop: problem stopping OSXvnc-server"
        exit -1
    fi
  fi
  exit 0
fi

if [ -x "$VNCPATH" ]; then
  ConsoleMessage "Starting OSXvnc Server"

  if [ -e /var/log/osxvnc.log ] ; then
    /bin/mv /var/log/osxvnc.log /var/log/osxvnc.log.1
  fi

  $0-keepalive $VNCPATH/OSXvnc-server $VNCARGS > /var/log/osxvnc.log 2>&1 &
  exit 0
else
  ConsoleMessage "Unable to find OSXvnc"
  exit -1
fi
