#!/bin/sh 
. /etc/rc.common

#
# OSXvnc
# 
# The OSXvnc application will OVERWRITE this file if you ask it to Setup the Startup Item
#

VNCPATH="/Applications/OSXvnc.app"
VNCARGS="-rfbport 5900 -rfbauth $VNCPATH/.osxvncauth -swapButtons -dontdisconnect"

#
# Modification Log:
#
# 1.33
# Added Resources directory with English.lproj for Localization lookup
# Modified to handle 'restart' directive
# Modified to make more better use of the awk command
#
# 1.31
# Modified Startup parameters to work better on some systems
# Modified so that OSXvnc can live in directories with spaces
#
# 1.3
# Modified so that OSXvnc app can configure
# Removed Usage
#
# 1.2
# Fixed problem in stop section (missing space)
# Fixed stop to also kill the server and keep alive
# Now Uses $VNCPATH for other arguments
#
# 1.11
# Added Usage Info
# Added keepalive call
#
# 1.0/Initial
# Initial Version, no # and no history
#
##

if [ ${1:-noset} == "setpassword" ]; then
    $VNCPATH/storepasswd "$2" $VNCPATH/.osxvncauth
    echo "Password set at path " $VNCPATH/.osxvncauth
    exit 0
fi

if [ ${1:-noset} == "stop" ] || [ ${1:-noset} == "restart" ]; then
    ConsoleMessage "Stopping OSXvnc KeepAlive"
    OSXVNCPID=`/bin/ps auxwwww | /usr/bin/awk '/[O]SXvnc-keepalive/ && NR > 2 {print $2}'`
    if [ "${OSXVNCPID:=""}" ]; then
        kill $OSXVNCPID
        sleep 1
    fi
    # make sure it's dead
    OSXVNCPID=`/bin/ps -auxwwww | /usr/bin/awk '/[O]SXvnc-keepalive/ && NR > 2 {print $2}'`
    if [ "${OSXVNCPID:=""}" != "" ]; then
        ConsoleMessage "OSXvnc $1: problem stopping OSXvnc-keepalive"
        exit -1
    fi

    ConsoleMessage "Stopping OSXvnc Server"
    OSXVNCPID=`/bin/ps -auxwwww | /usr/bin/awk '/[O]SXvnc-server/ && NR > 2 {print $2}'`
    if [ "${OSXVNCPID:=""}" ]; then
        kill $OSXVNCPID
        sleep 1
    fi
    # make sure it's dead
    OSXVNCPID=`/bin/ps -auxwwww | /usr/bin/awk '/[O]SXvnc-server/ && NR > 2 {print $2}'`
    if [ "${OSXVNCPID:=""}" != "" ]; then
        ConsoleMessage "OSXvnc $1: problem stopping OSXvnc-server $OSXVNCPID"
        exit -1
    fi
    if [ ${1:-noset} = "stop" ]; then
        exit 0
    fi
fi


if [ -x "$VNCPATH" ]; then
    ConsoleMessage "Starting OSXvnc Server"

    if [ -e /var/log/osxvnc.log ]; then
        /bin/mv /var/log/osxvnc.log /var/log/osxvnc.log.1
    fi

    $0-keepalive "$VNCPATH/OSXvnc-server" $VNCARGS > /var/log/osxvnc.log 2>&1 &
else
    ConsoleMessage "Unable to find OSXvnc"
    exit -1
fi
